### ISSUE TITLE
Enter/Return key on verification text reload the page

### ISSUE THREAD

**Issue by IMPMAC** [Godofbrowser/vuejs-dialog#17]
If you go to the demo, scroll to the "Hard confirm - verification text required" button and click.

Then click in the verification box, press enter or return on the keyboard,  it submits the form and refreshes the page.

I expect it to ignore the form submit

**Comment by Godofbrowser** [comment]
Obviously, that is a bug. Thanks! fixing immediately...

**Comment by IMPMAC** [comment]
@Godofbrowser Thanks, I guess Ill be notified by Github when its pushed.

Keep up the good work!

**Comment by Godofbrowser** [comment]
@IMPMAC [1 new github notification](https://github.com/Godofbrowser/vuejs-dialog/commit/fd48c1517e0d64e2b7f6711e439d5215b40f50e6) 😀

**Comment by Godofbrowser** [comment]
Closing as the issue has been fixed.

**Comment by IMPMAC** [comment]
@Godofbrowser Yep, I can confirm in my testing that this issue has been fixed.

**Comment by IMPMAC** [comment]
Hi, somewhat related to this, could you add a parameter to disable Chromes autocomplete feature. I believe its autocomplete="false" to add to the input field.

This is because once you type in "reset" the first time, the second time, it will automatically give you a drop down with the word "reset' inside.

Thanks.

**Comment by Godofbrowser** [comment]
Its very necessary. Would fix that asap.  Thanks.

On Feb 22, 2018 5:11 PM, "Ismail Patel" <notifications@github.com> wrote:

Hi, somewhat related to this, could you add a parameter to disable Chromes
autocomplete feature. I believe its autocomplete="false" to add to the
input field.

This is because once you type in "reset" the first time, the second time,
it will automatically give you a drop down with the word "reset' inside.

Thanks.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Godofbrowser/vuejs-dialog/issues/17#issuecomment-367731506>,
or mute the thread
